---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
  labels: 
    app: kibana
data:
  kibana.yml: |
    server.ssl:
      enabled: false
      key: /usr/share/kibana/config/certs/tls.key
      certificate: /usr/share/kibana/config/certs/tls.crt
    xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.encryptedSavedObjects.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    xpack.reporting.encryptionKey: ${KIBANA_ENCRYPTION_KEY}
    monitoring.ui.container.elasticsearch.enabled: true
    elasticsearch.ssl:
      certificateAuthorities: /usr/share/kibana/config/certs/ca.crt
      verificationMode: certificate
